name: Latest iOS build check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: macos-15

    steps:
      
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Check build for the latest iOS
    - name: Check build for latest iOS
      run: ./.scripts/build-check.sh --device-type ipad --scheme ClearFunds

    # Run tests on iPad Pro Simulator with latest iOS
    - name: Run tests on iPad Pro Simulator
      run: ./.scripts/build-check.sh --scheme 'ClearFunds' --type test --device-type ipad
